[package]
name = "wgpu-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png_pong = "0.8"
pix = "0.13"
wgpu = "0.14"
pasts = "0.12"
whisk = "0.9"
